version: 0.1.1-appveyor{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2013
platform: x64
clone_folder: c:\zest_build
install:
- ps: >-
    Install-Product node 5.1.1 x64

    nuget install packages.config

    cmd /c "scripts\build_deps 2>&1"
build_script:
- cmd: scripts\build_app
artifacts:
- path: builds\zest-v*\zest-v*.exe
cache:
- C:\Libraries\boost_1_59_0\stage\lib
- C:\Libraries\boost_1_59_0\bin.v2
- LucenePlusPlus
- libarchive
- sogrep-src
- nodelucene
